services:
  mongo:
    image: mongo:7.0  # Official image with proper permissions
    hostname: mongo
    ports:
      - "30001:27017"  # Map host port to container's default port
    command:
      - --replSet=my-replica-set
      - --bind_ip_all
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    healthcheck:
      test: |
        mongosh --quiet --eval "
          try {
            rs.status().ok
          } catch {
            rs.initiate()
          }"
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s  # Allow ample time for initialization

  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/booking?replicaSet=my-replica-set
    depends_on:
      mongo:
        condition: service_healthy
    command: npm run dev

volumes:
  mongo_data:
  mongo_config:
  node_modules:
